image: ruby:latest

variables:
  JEKYLL_ENV: production

cache:
  paths:
  - vendor/

before_script:
- gem install bundler
- bundle install --path vendor

pages:
  script:
  - bundle e jekyll b -d public
  artifacts:
    paths:
    - public
  only:
  - master
